### Code

### Main Documentation
- [Documentation](https://docs.google.com/document/d/1rUQ_eqxU_jSBXNykCA0-_navj3nZ_veKjVMPY5Q5n-4/edit?tab=t.0)

### Reference
- [y_finance API documentation](https://ranaroussi.github.io/yfinance/reference/yfinance.ticker_tickers.html)  
- [y_finance complete guide](https://algotrading101.com/learn/yfinance-guide/)  
- [9 Alternative Finance API](https://algotrading101.com/learn/google-finance-api-guide/)

In [ ]:
import yfinance as yf
import pandas as pd
# import plotly.graph_objects as go
# from plotly.subplots import make_subplots
# import ipywidgets as widgets
# from IPython.display import display, clear_output

In [ ]:
STOCK_TICKERS = ["AAPL", "TSLA", "PLTR", "NKE", "NVDA", "GOOGL", "AMZN", "IBM", "ORCL", "NFLX", "AMD", "INTC", "QCOM", "TEM", "CRM", "AVGO", "MU", "SNDK", "EQIX" ]

TOP_200_US_TICKERS = [
    "AAPL","MSFT","NVDA","AMZN","GOOGL","GOOG","META","BRK-B","TSLA","LLY",
    "AVGO","JPM","V","MA","UNH","XOM","JNJ","HD","PG","COST",
    "ABBV","MRK","PEP","KO","ADBE","CRM","AMD","ORCL","NFLX","WMT",
    "BAC","CSCO","ACN","MCD","TMO","LIN","DHR","ABT","TXN","NEE",
    "PM","RTX","QCOM","UPS","LOW","INTU","AMGN","HON","IBM","SBUX",
    "CAT","GS","ISRG","NOW","BLK","MDT","DE","ADI","GILD","SYK",
    "LRCX","MU","PLD","ADP","CB","ELV","PGR","REGN","VRTX",
    "CI","C","MDLZ","MO","SCHW","ZTS","EOG","BDX","CSX","NOC",
    "PNC","CL","SO","DUK","ITW","FDX","SHW","APD","HCA","WM",
    "ICE","USB","TGT","MCK","EW","ROP","EMR","FIS","GD","AON",
    "ETN","PH","CMCSA","MS","KLAC","MAR","AZO","PSA","AEP","CTAS",
    "ORLY","TRV","SPGI","MPC","KMB","OXY","SLB","VLO","AIG","PAYX",
    "BK","COF","F","GM","DAL","UAL","LUV","EXC","XEL","SRE",
    "D","PEG","WEC","ED","ES","EIX","PCAR","ROK","FAST","ODFL",
    "TT","CARR","OTIS","JCI","URI","AME","CTSH","ANET","PANW","CRWD",
    "SNOW","DDOG","NET","TEAM","ZS","OKTA","MDB","DOCU","SHOP",
    "PYPL","UBER","ABNB","LYFT","RBLX","PLTR","COIN","HOOD","AFRM","SOFI",
    "INTC","HPQ","DELL","SMCI","ASML","TSM","NXPI","ON","MPWR","SWKS",
    "WDAY","ADSK","CDNS","SNPS","FTNT","CHTR","TMUS","VZ","T","DIS",
    "CMG","YUM","DPZ","DRI","SYY","KR","DG","DLTR","ROST","TJX",
    "KDP","MNST","STZ","BF-B","GIS","HSY","KHC","CPB","MKC","TSN"
]

IMPORTANT_FIELDS = [
    # Company Identity
    "symbol", "shortName", "sector", "industry",

    # Valuation Metrics
    "marketCap","currentPrice","forwardPE", "pegRatio", "enterpriseToEbitda", "priceToBook",

    # Growth Metrics
    "revenueGrowth","earningsGrowth","forwardEps",

    # Profitability Metrics
    "profitMargins", "returnOnEquity", "operatingMargins", "grossMargins",

    # Finanacial Strangth
    "freeCashflow", "debtToEquity", "totalCash", "totalDebt",

    # Market Risk & Liquidity
    "beta","averageVolume",

    # Ownership & Market Sentiment
    "heldPercentInstitutions", "shortPercentOfFloat",

    # Analyst Expectations
    "targetMeanPrice", "recommendationKey",

    # Dividend & Payout
    "trailingAnnualDividendYield", "payoutRatio"

    # Custom
]


DISPALY_COLUMN_NAME_MAPPING = {
  "symbol": "Ticker",
  "shortName": "Name",
  "sector": "Sector",
  "industry": "Industry",
  "marketCap": "Market Cap",
  "currentPrice": "Price",
  "forwardPE": "Forward PE",
  "trailingPE": "Trailing PE",
  "pegRatio": "PEG",
  "enterpriseToEbitda": "EV/EBITDA",
  "priceToBook": "Price to Book",
  "revenueGrowth": "Revenue Growth",
  "earningsGrowth": "Earnings Growth",
  "forwardEps": "Forward EPS",
  "profitMargins": "Profit Margin",
  "operatingMargins": "OP Margin",
  "returnOnEquity": "ROE",
  "freeCashflow": "Free Cashflow",
  "totalCash": "Total Cash",
  "totalDebt": "Total Debt",
  "debtToEquity": "Debt to Equity",
  "beta": "Beta",
  "averageVolume": "Avg. Volume",
  "heldPercentInstitutions": "Insr. Ownership",
  "shortPercentOfFloat": "Short Float",
  "targetMeanPrice": "Target Price",
  "recommendationKey": "Recommendation",
  "numberOfAnalystOpinions": "Analyst Opinions",
  "averageAnalystRating": "Analyst Rating",
  "trailingAnnualDividendYield": "Dividend Yield",
  "payoutRatio": "Payout Ratio",
}

SELECTED_FIELDS = [
    "shortName", "sector", "industry",
    "marketCap","currentPrice","forwardPE","pegRatio",
    "revenueGrowth","earningsGrowth","forwardEps",
    "profitMargins","returnOnEquity",
    "freeCashflow","debtToEquity",
    "beta","averageVolume",
    "heldPercentInstitutions","shortPercentOfFloat",
    "trailingAnnualDividendYield","payoutRatio"
]

In [ ]:
# TODO : Optimize add_stocks to use tickers.
def add_stock(df: pd.DataFrame, ticker_symbol: str) -> pd.DataFrame:
    ticker = yf.Ticker(ticker_symbol)
    info = ticker.info

    row = {
        field: info.get(field, None)
        for field in IMPORTANT_FIELDS
    }

    new_row = pd.DataFrame([row])

    return pd.concat([df, new_row], ignore_index=True)

def add_stocks(df: pd.DataFrame, stock_tickers) -> pd.DataFrame:
    for ticker in stock_tickers:
        df = add_stock(df, ticker)
    return df


def abbreviateNumber(value: float):
    if pd.isna(value):
        return value

    abs_value = abs(value)

    if abs_value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f}B"
    elif abs_value >= 1_000_000:
        return f"{value / 1_000_000:.2f}M"
    elif abs_value >= 1_000:
        return f"{value / 1_000:.2f}K"
    else:
        return f"{value:.2f}"

# Define column groups
financial_cols = ['marketCap', 'currentPrice', 'forwardEps', "freeCashflow", 'totalCash', "totalDebt", "freeCashflow"]

percentage_cols = [
    'revenueGrowth', 'earningsGrowth', 'profitMargins',
    'operatingMargins', 'returnOnEquity', 'heldPercentInstitutions', 'shortPercentOfFloat','trailingAnnualDividendYield',
]

def format_df(df: pd.DataFrame) -> pd.DataFrame:

    formatted_df = df.copy()

    # def abbreviate_currency(value):
    #     if pd.isna(value) or not isinstance(value, (int, float)):
    #         return value
    #     abs_val = abs(value)
    #     if abs_val >= 1e12: return f"${value/1e12:.2f}T"
    #     if abs_val >= 1e9:  return f"${value/1e9:.2f}B"
    #     if abs_val >= 1e6:  return f"${value/1e6:.2f}M"
    #     if abs_val >= 1e3:  return f"${value/1e3:.2f}K"
    #     return f"${value:.2f}"

    # def format_pct(value):
    #     if pd.isna(value) or not isinstance(value, (int, float)):
    #         return value
    #     return f"{value * 100:.2f}%"

    # def format_float(value):
    #     if pd.isna(value) or not isinstance(value, (int, float)):
    #         return value
    #     return f"{value:.2f}"

    # # 1. Apply currency formatting
    # for col in financial_cols:
    #     if col in formatted_df.columns:
    #         formatted_df[col] = formatted_df[col].apply(abbreviate_currency)

    # # 2. Apply percentage formatting
    # for col in percentage_cols:
    #     if col in formatted_df.columns:
    #         formatted_df[col] = formatted_df[col].apply(format_pct)

    # # 3. Apply standard float formatting (DD.DD) to remaining numeric columns
    # numeric_cols = formatted_df.select_dtypes(include=['number']).columns
    # remaining_cols = [c for c in numeric_cols if c not in financial_cols and c not in percentage_cols]

    # for col in remaining_cols:
    #     # Skip columns that might be counts (like Average Volume) if preferred,
    #     # but applying DD.DD as requested for all floats.
    #     formatted_df[col] = formatted_df[col].apply(format_float)

    # Rename columns
    stocks.rename(columns=DISPALY_COLUMN_NAME_MAPPING, inplace=True)

    return formatted_df


    # Generate stocks dataframe
def generate_stocks_df(stock_tickers):

  # Create df w/ full IMPORTANT_FIELDS columns
  stocks = pd.DataFrame(columns=IMPORTANT_FIELDS)

  stocks = add_stocks(stocks, stock_tickers)

  # Reset index to Ticker
  stocks.set_index("symbol", inplace=True)

  # Select columns to be displayed
  stocks = stocks[SELECTED_FIELDS]

  # Format data - Display Format & Renaming Cols
  stocks = format_df(stocks)

  return stocks

# Actual

## General information Dashboard

- Goal : Compare stocks with important metrics // TODO
- Source : **Ticker.info**
- Output : Dataframe
- limitation : only 20 fields are allowed to be displayed at once on colab

In [ ]:
stocks = generate_stocks_df(STOCK_TICKERS)
stocks

## yfinance API analysis

### Note
- **ticker.history(period, interval, proxy)**
  - range of intervals: 1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo

### Ticker.info

#### 📊 Interpreting `yfinance.ticker.info` Fields for Stock Evaluation

This guide summarizes how professional investors interpret key `ticker.info` properties when evaluating a company for investment decisions.

---

### 🧠 1. Company Overview

| Field | Interpretation |
|---|---|
| `longName` / `shortName` | Company identity |
| `sector` | Macro classification (Technology, Healthcare, etc.) |
| `industry` | Direct competitors & valuation comparison group |
| `longBusinessSummary` | Business model understanding |
| `fullTimeEmployees` | Operational scale & maturity |

✅ Used for **business understanding + peer comparison**

---

### 💰 2. Valuation Metrics (Is the Stock Expensive?)

| Field | Interpretation |
|---|---|
| `marketCap` | Company size (risk profile & fund eligibility) |
| `enterpriseValue` | True company value including debt |
| `trailingPE` | Price relative to past earnings |
| `forwardPE` | Expected valuation based on forecasts |
| `priceToSalesTrailing12Months` | Useful when profits are volatile |
| `priceToBook` | Asset valuation efficiency |
| `pegRatio` | Valuation adjusted for growth |

✅ Goal: Determine **cheap vs overpriced**

**Typical Signals**
- Lower PE relative to growth → attractive
- PEG ≈ 1 → fairly valued
- Very high multiples → growth expectations priced in

---

### 📈 3. Growth Metrics (Future Potential)

| Field | Interpretation |
|---|---|
| `revenueGrowth` | Sales expansion rate |
| `earningsGrowth` | Profit growth sustainability |
| `earningsQuarterlyGrowth` | Near-term momentum |
| `forwardEps` | Expected profitability |
| `revenuePerShare` | Revenue efficiency |

✅ Growth drives long-term stock returns.

**Healthy Company**
- Revenue growth > 5–10%
- Earnings growth ≥ revenue growth

---

### 🏆 4. Profitability & Business Quality

| Field | Interpretation |
|---|---|
| `profitMargins` | Net profitability |
| `grossMargins` | Pricing power |
| `operatingMargins` | Operational efficiency |
| `returnOnAssets` | Asset utilization |
| `returnOnEquity` | Capital efficiency (elite metric) |
| `ebitdaMargins` | Core operating strength |

✅ High margins + high ROE = **quality company**

---

### 💵 5. Cash Flow & Financial Strength

| Field | Interpretation |
|---|---|
| `freeCashflow` | Real cash generated for investors |
| `operatingCashflow` | Cash from core operations |
| `totalCash` | Liquidity buffer |
| `totalDebt` | Financial obligations |
| `debtToEquity` | Leverage risk |
| `currentRatio` | Short-term solvency |
| `quickRatio` | Immediate liquidity health |

✅ Companies survive recessions through **cash flow strength**.

---

### ⚖️ 6. Risk & Volatility

| Field | Interpretation |
|---|---|
| `beta` | Market volatility vs S&P 500 |
| `overallRisk` | Governance risk assessment |
| `auditRisk` | Accounting reliability |
| `boardRisk` | Board independence quality |
| `compensationRisk` | Executive incentive alignment |

**Beta Guide**
- < 1 → defensive
- ≈ 1 → market-like
- > 1.5 → high volatility

---

### 🧲 7. Ownership & Market Sentiment

| Field | Interpretation |
|---|---|
| `heldPercentInstitutions` | Institutional confidence |
| `heldPercentInsiders` | Management alignment |
| `sharesShort` | Bearish positioning |
| `shortPercentOfFloat` | Short squeeze potential |
| `shortRatio` | Days needed to cover shorts |

✅ Institutions often signal **smart money interest**.

---

### 📊 8. Analyst Expectations

| Field | Interpretation |
|---|---|
| `targetMeanPrice` | Consensus valuation |
| `targetHighPrice` | Bull case |
| `targetLowPrice` | Bear case |
| `recommendationMean` | Analyst rating score |
| `numberOfAnalystOpinions` | Confidence level |

Typical Scale:
- 1 → Strong Buy
- 2 → Buy
- 3 → Hold
- 4 → Sell

---

### 📉 9. Trading & Liquidity Metrics

| Field | Interpretation |
|---|---|
| `averageVolume` | Liquidity for entry/exit |
| `volume` | Current trading interest |
| `fiftyDayAverage` | Medium trend |
| `twoHundredDayAverage` | Long-term trend |
| `52WeekHigh` / `52WeekLow` | Price positioning |

✅ Used for timing entries.

---

### 🏦 10. Balance Sheet Efficiency

| Field | Interpretation |
|---|---|
| `bookValue` | Net assets per share |
| `enterpriseToRevenue` | Revenue valuation efficiency |
| `enterpriseToEbitda` | Operating valuation multiple |

---

### ⭐ Professional Evaluation Checklist

#### ✔ Quality Company
- ROE > 15%
- Positive free cash flow
- Stable margins
- Growing earnings

#### ✔ Attractive Valuation
- Forward PE reasonable
- PEG near 1–2
- EV/EBITDA competitive vs peers

#### ✔ Financial Safety
- Debt manageable
- Strong liquidity ratios

#### ✔ Market Confirmation
- Institutional ownership high
- Analyst outlook positive

In [ ]:
ticker = yf.Ticker("AAPL")

# general info
# ticker.info

# get financials
# ticker.balance_sheet
# dat.quarterly_income_stmt

# get historical market data
# ticker.history(period='1mo', interval="1h")

# options
# ticker.option_chain(dat.options[0]).calls

# analysis
# ticker.analyst_price_targets

# dates
# ticker.calendar

# actions
# ticker.actions

# websocket
# dat.live()

In [ ]:
# Create a dictionary of property descriptions for ticker.info
info_description = {

    'irWebsite': 'Investor Relations website URL.',
    'industry': 'Specific business niche within a sector.',
    'sector': 'Broad economic category of the company.',
    'longBusinessSummary': 'Detailed narrative of company operations and history.',

    # Risk
    'auditRisk': 'Numeric score (1-10) for accounting/auditing risk.',
    'boardRisk': 'Numeric score for board effectiveness risk.',
    'compensationRisk': 'Numeric score for executive pay practice risk.',
    'shareHolderRightsRisk': 'Numeric score for shareholder interest protection risk.',
    'overallRisk': 'Aggregated corporate governance risk score.',

    'maxAge': 'Cache TTL in seconds for the data.',
    'priceHint': 'Suggested decimal precision for displaying price.',
    'previousClose': 'Closing price of the previous trading day.',
    'open': 'Opening price of the current session.',
    'dayLow': 'Lowest price during the current session.',
    'dayHigh': 'Highest price during the current session.',
    'regularMarketPreviousClose': 'Previous close during regular trading hours.',
    'regularMarketOpen': 'Opening price during regular trading hours.',
    'regularMarketDayLow': 'Lowest price during regular trading hours.',
    'regularMarketDayHigh': 'Highest price during regular trading hours.',
    'dividendRate': 'Expected annual dividend payment per share.',
    'dividendYield': 'Annual dividend as a percentage of stock price.',
    'exDividendDate': 'Date by which you must own shares to receive the next dividend.',
    'payoutRatio': 'Percentage of earnings paid out as dividends.',
    'fiveYearAvgDividendYield': 'Average dividend yield over the last five years.',
    'beta': 'Volatility measure relative to the broader market.',
    'trailingPE': 'Price-to-earnings ratio using last 12 months earnings.',
    'forwardPE': 'Price-to-earnings ratio using projected next-year earnings.',
    'volume': 'Shares traded during the current session.',
    'regularMarketVolume': 'Shares traded during regular market hours.',
    'averageVolume': 'Average daily trading volume.',
    'averageVolume10days': 'Average daily trading volume over the last 10 days.',
    'averageDailyVolume10Day': 'Redundant 10-day average volume metric.',
    'bid': 'Highest price buyers are willing to pay.',
    'ask': 'Lowest price sellers are willing to accept.',
    'bidSize': 'Number of shares requested at the bid price.',
    'askSize': 'Number of shares offered at the ask price.',
    'marketCap': 'Total market value of all outstanding shares.',
    'fiftyTwoWeekLow': 'Lowest price in the last 52 weeks.',
    'fiftyTwoWeekHigh': 'Highest price in the last 52 weeks.',
    'priceToSalesTrailing12Months': 'Market cap divided by trailing 12-month revenue.',
    'fiftyDayAverage': 'Average closing price over the last 50 days.',
    'twoHundredDayAverage': 'Average closing price over the last 200 days.',
    'trailingAnnualDividendYield': 'Actual dividends paid over last year divided by price.',
    'currency': 'Currency code for all financial values (e.g., USD).',
    'enterpriseValue': 'Total company value including debt minus cash.',
    'profitMargins': 'Net profit as a percentage of revenue.',
    'floatShares': 'Number of shares available for public trading.',
    'sharesOutstanding': 'Total number of issued shares.',
    'sharesShort': 'Total shares currently sold short.',
    'sharesShortPriorMonth': 'Short interest from the previous reporting month.',
    'sharesShortPreviousMonthDate': 'Date of the previous month short interest data.',
    'dateShortInterest': 'Date the current short interest was recorded.',
    'sharesPercentSharesOut': 'Percentage of total shares sold short.',
    'heldPercentInsiders': 'Percentage of shares owned by company insiders.',
    'heldPercentInstitutions': 'Percentage of shares owned by institutional investors.',
    'shortRatio': 'Days to cover short positions based on average volume.',
    'shortPercentOfFloat': 'Percentage of the tradable float sold short.',
    'bookValue': 'Net asset value divided by total shares.',
    'priceToBook': 'Stock price divided by book value per share.',
    'lastFiscalYearEnd': 'Date of the company’s last fiscal year end.',
    'nextFiscalYearEnd': 'Date of the company’s next fiscal year end.',
    'mostRecentQuarter': 'Date of the most recently reported fiscal quarter.',
    'earningsQuarterlyGrowth': 'Year-over-year growth in quarterly net income.',
    'netIncomeToCommon': 'Net income available to common stockholders.',
    'trailingEps': 'Earnings per share over the last 12 months.',
    'forwardEps': 'Projected earnings per share for the next year.',
    'pegRatio': 'P/E ratio divided by earnings growth rate.',
    'lastSplitFactor': 'Ratio of the most recent stock split.',
    'lastSplitDate': 'Date of the most recent stock split.',
    'enterpriseToRevenue': 'Enterprise value divided by total revenue.',
    'enterpriseToEbitda': 'Enterprise value divided by EBITDA.',
    '52WeekChange': 'Price change of the asset over 52 weeks.',
    'SandP52WeekChange': 'Price change of the S&P 500 over 52 weeks.',
    'lastDividendValue': 'Value of the most recent dividend payment.',
    'lastDividendDate': 'Date of the most recent dividend payment.',
    'quoteType': 'Type of security (e.g., EQUITY, ETF).',
    'currentPrice': 'The most recent trading price.',
    'targetHighPrice': 'Highest analyst price target.',
    'targetLowPrice': 'Lowest analyst price target.',
    'targetMeanPrice': 'Average analyst price target.',
    'targetMedianPrice': 'Median analyst price target.',
    'recommendationMean': 'Consensus analyst rating score (1 to 5).',
    'recommendationKey': 'Consensus rating summary (e.g., buy, hold).',
    'numberOfAnalystOpinions': 'Number of analysts providing coverage.',
    'totalCash': 'Total cash and equivalents on the balance sheet.',
    'totalCashPerShare': 'Total cash divided by total shares.',
    'ebitda': 'Earnings before interest, taxes, depreciation, and amortization.',
    'totalDebt': 'Total debt obligations on the balance sheet.',
    'quickRatio': 'Liquidity measure excluding inventory.',
    'currentRatio': 'Ability to cover short-term liabilities with current assets.',
    'totalRevenue': 'Total company revenue.',
    'debtToEquity': 'Total debt relative to shareholder equity.',
    'revenuePerShare': 'Total revenue divided by total shares.',
    'returnOnAssets': 'Net income divided by total assets.',
    'returnOnEquity': 'Net income divided by shareholder equity.',
    'grossProfits': 'Total revenue minus cost of goods sold.',
    'freeCashflow': 'Operating cash flow minus capital expenditures.',
    'operatingCashflow': 'Cash generated from core business operations.',
    'earningsGrowth': 'Year-over-year increase in company earnings.',
    'revenueGrowth': 'Year-over-year increase in company revenue.',
    'grossMargins': 'Gross profit as a percentage of revenue.',
    'ebitdaMargins': 'EBITDA as a percentage of revenue.',
    'operatingMargins': 'Operating income as a percentage of revenue.',
    'financialCurrency': 'Currency used in financial statements.',
    'symbol': 'Stock ticker symbol.',
    'language': 'Language of the data response.',
    'region': 'Geographic region of the listing.',
    'typeDisp': 'Human-readable security type description.',
    'quoteSourceName': 'Original source of the price quote.',
    'triggerable': 'Indicates if the quote can trigger system alerts.',
    'customPriceAlertConfidence': 'Confidence score for price alert accuracy.',
    'regularMarketChange': 'Price change during regular market hours.',
    'regularMarketChangePercent': 'Percentage price change during regular hours.',
    'regularMarketPrice': 'Current price during regular market hours.',
    'marketState': 'Status of the market (e.g., OPEN, CLOSED, PREPRE).',
    'shortName': 'Common abbreviated name of the company.',
    'longName': 'Full legal name of the company.',
    'fiftyDayAverageChange': 'Difference between current price and 50-day average.',
    'fiftyDayAverageChangePercent': 'Percentage change from 50-day average.',
    'twoHundredDayAverageChange': 'Difference between current price and 200-day average.',
    'twoHundredDayAverageChangePercent': 'Percentage change from 200-day average.',
    'sourceInterval': 'Update interval in minutes from the source.',
    'exchangeDataDelayedBy': 'Minutes of delay in the data feed.',
    'averageAnalystRating': 'Text summary of analyst consensus rating.',
    'cryptoTradeable': 'Indicates if the asset is tradeable on crypto exchanges.',
    'corporateActions': 'List of corporate events like splits and dividends.',
    'postMarketTime': 'Timestamp of the last post-market trade.',
    'regularMarketTime': 'Timestamp of the last regular market trade.',
    'exchange': 'Exchange identifier where stock is listed.',
    'messageBoardId': 'ID for the stock on financial message boards.',
    'exchangeTimezoneName': 'Full name of the exchange timezone.',
    'exchangeTimezoneShortName': 'Abbreviation of the exchange timezone.',
    'gmtOffSetMilliseconds': 'Timezone offset from GMT in milliseconds.',
    'market': 'Market category identifier.',
    'esgPopulated': 'Indicates if ESG data is available for this ticker.',
    'fiftyTwoWeekChangePercent': 'Percentage change in price over 52 weeks.',
    'dividendDate': 'Timestamp of the next/last dividend payment.',
    'earningsTimestamp': 'Timestamp of the earnings announcement.',
    'earningsTimestampStart': 'Earliest expected earnings announcement time.',
    'earningsTimestampEnd': 'Latest expected earnings announcement time.',
    'earningsCallTimestampStart': 'Scheduled start of the earnings conference call.',
    'earningsCallTimestampEnd': 'Scheduled end of the earnings conference call.',
    'isEarningsDateEstimate': 'Indicates if the earnings date is an estimate.',
    'epsTrailingTwelveMonths': 'Trailing 12-month earnings per share.',
    'epsForward': 'Forward-looking earnings per share.',
    'epsCurrentYear': 'Analyst estimate for current year EPS.',
    'priceEpsCurrentYear': 'Price divided by current year estimated EPS.',
    'hasPrePostMarketData': 'Indicates if pre/post market data is available.',
    'firstTradeDateMilliseconds': 'Timestamp of the first trade ever recorded.',
    'postMarketChangePercent': 'Percentage change in after-hours trading.',
    'postMarketPrice': 'Current after-hours price.',
    'postMarketChange': 'Price change in after-hours trading.',
    'fullExchangeName': 'The full legal name of the exchange.',
    'averageDailyVolume3Month': 'Average daily trading volume over last 3 months.',
    'fiftyTwoWeekLowChange': 'Difference from current price to 52-week low.',
    'fiftyTwoWeekLowChangePercent': 'Percentage increase from 52-week low.',
    'fiftyTwoWeekRange': 'The high-low spread over the past year.',
    'fiftyTwoWeekHighChange': 'Difference from current price to 52-week high.',
    'fiftyTwoWeekHighChangePercent': 'Percentage decrease from 52-week high.',
    'displayName': 'Company name displayed in user interfaces.',
    'trailingPegRatio': 'Trailing PEG ratio (P/E / growth).',
    'allTimeHigh': 'Highest price reached in the history of the stock.',
    'allTimeLow': 'Lowest price reached in the history of the stock.',
    'trailingAnnualDividendRate': 'Total dividends paid per share in the last year.',
    'tradeable': 'Indicates if the stock is currently eligible for trading.',
    'executiveTeam': 'List of primary corporate executives and roles.',
    'nonDilutedMarketCap': 'Market cap calculated without accounting for dilutive securities.',
    'impliedSharesOutstanding': 'Shares including potential stock options.',
    'regularMarketDayRange': 'Intraday price spread.'
}

# Playground

### Gernal Info Dashboard - Column Descriptions

This guide explains **each field in `IMPORTANT_FIELDS`**, what it measures, and **how investors interpret it** when comparing stocks.


#### **Four Pillars** of Evaluation:

1. Valuation > Is the price reasonable?
2. Growth > Can earnings expand?
3. Quality > Is the business strong?
4. Risk > Can it survive downturns?

---

#### ⭐ Example Decision Logic

**Great Investment Candidate**
- Reasonable Forward PE
- Growing Revenue & earnings
- High ROE
- Positive free cash flow
- Strong institutional ownership

**Potential Value Trap** ➡ Low PE & Weak growth & Declining margins & High debt

---

---

#### 🧠 Company Identity

- **symbol :** Stock ticker symbol  
- **longName :** Full company name  
- **sector :** Broad economic sector classification  
- **industry :** Specific industry classification  

**How to interpret**
- Always compare valuation & margins **within the same sector/industry**.

---

#### 💰 Valuation Metrics (Is the Stock Cheap?)

- **currentPrice :** Latest trading price  
- **marketCap :** Total market value of all shares outstanding → Indicates company size.  
- **forwardPE :** Price divided by expected future earnings → Market expectations of future valuation.  
- **trailingPE :** Price divided by past earnings → Historical valuation measure.  
- **pegRatio :** PE ratio adjusted for earnings growth → Valuation relative to growth.  
- **enterpriseToEbitda :** Enterprise value divided by EBITDA → Capital-structure neutral valuation metric.  
- **priceToBook :** Price relative to company net assets → Measures asset valuation.

**How to interpret**
- Lower PE ≠ better automatically.
- PEG ≈ **1** → fairly valued growth.
- EV/EBITDA useful for cross-company comparison.
- High P/B acceptable for asset-light businesses (software).

**Typical ranges:**

| Metric | Attractive |
|---|---|
| Forward PE | < 20 (sector dependent) |
| PEG | 0.8–1.5 |
| EV/EBITDA | < 15 |

---

#### 🚀 Growth Metrics (Future Expansion)

**revenueGrowth :** Year-over-year revenue growth rate → Demand expansion signal.  
**earningsGrowth :** Profit growth rate → Operating leverage efficiency.  
**forwardEps :** Expected future earnings per share → Analyst projection of profitability.  

**How to interpret**
- Revenue growth = business demand.
- Earnings growth > revenue growth = improving efficiency.
- Sustainable growth matters more than spikes.

Typical signals:

- 5–10% → Mature company  
- 10–20% → Healthy growth  
- 20%+ → High-growth company

---

#### 🏆 Profitability Metrics (Business Quality)

**profitMargins :** Net income as % of revenue → Overall profitability.  
**operatingMargins :** Core business efficiency before financing/taxes  
**returnOnEquity (ROE) :** Profit generated from shareholder capital → One of the most important quality metrics.  

**How to interpret**
- Higher margins indicate competitive advantage.
- High ROE signals efficient capital allocation.

Strong benchmarks:

| Metric | Strong |
|---|---|
| Profit Margin | >10% |
| Operating Margin | >15% |
| ROE | >15% |

---

#### 💵 Financial Strength (Balance Sheet Health)

**freeCashflow :** Cash remaining after investments → Real money available to investors.  
**totalCash :** Cash reserves on balance sheet → Financial safety buffer.  
**totalDebt :** Total borrowing obligations → Financial risk level.  
**debtToEquity :** Debt relative to shareholder equity → Leverage measurement.  

**How to interpret**
- Positive free cash flow = sustainable business.
- High debt acceptable only with stable cash flows.
- Cash-rich companies survive downturns.

General guidance:

| Metric | Healthy |
|---|---|
| Debt/Equity | < 100 |
| Free Cash Flow | Positive & growing |

---

#### 📈 Market Risk & Liquidity

**beta :** Volatility relative to overall market → Risk measurement.  
**averageVolume :** Average shares traded daily → Liquidity indicator.  

**How to interpret**
- Beta > 1 → more volatile than market.
- Beta < 1 → defensive stock.
- High volume = easier entry/exit.

Typical use:
- Growth investors tolerate high beta.
- Capital preservation prefers low beta.

---

#### 🏦 Ownership & Market Sentiment

**heldPercentInstitutions :** % owned by funds and institutions → Professional investor confidence.  
**shortPercentOfFloat :** % of shares sold short → Bearish sentiment indicator.  

**How to interpret**
- High institutional ownership = validation.
- Rising short interest = potential risk or short squeeze.

Guidelines:

| Metric | Meaning |
|---|---|
| Institutional >60% | Strong institutional support |
| Short Float >10% | Market skepticism |
| Short Float >20% | High risk / squeeze potential |

---

#### 🎯 Analyst Expectations

**targetMeanPrice :** Average analyst price target  
**recommendationKey :** Consensus rating (buy/hold/sell) → Market sentiment summary.  
**numberOfAnalystOpinions :** Number of analysts covering stock → Reliability of consensus.

**How to interpret**
- Large upside vs price may indicate opportunity OR hype.

---

#### 💸 Dividend & Shareholder Returns

**trailingAnnualDividendYield :** Dividend return relative to stock price → Income generation capability.  
**payoutRatio :** Portion of earnings paid as dividends → Dividend sustainability.

**How to interpret**
- High yield attractive for income investors.
- Extremely high payout ratio may signal risk.

Healthy ranges:

| Metric | Healthy |
|---|---|
| Dividend Yield | 2–5% |
| Payout Ratio | 30–60% |

---

#### IMPORTANT_FIELDS — Property Descriptions

#### Identity & Classification
Ticker : Stock trading symbol  
LongName : Official company name  
Sector : High-level economic sector classification  
Industry : Specific industry within sector  

#### Size & Market Position
MarketCap : Total market value of company equity  
EnterpriseValue : Company value including debt minus cash  

#### Valuation Metrics
TrailingPE : Price relative to last 12 months earnings  
ForwardPE : Price relative to expected future earnings  
PEG : PE adjusted by earnings growth rate  
PriceToBook : Price compared to book value of assets  
PriceToSales : Price compared to company revenue  

#### Growth Metrics
RevenueGrowth : Year-over-year revenue growth rate  
EarningsGrowth : Year-over-year earnings growth rate  
EarningsQuarterlyGrowth : Quarterly earnings growth trend  

#### Profitability Metrics
ProfitMargins : Net profit percentage of revenue  
OperatingMargins : Profit from operations before interest/taxes  
ReturnOnEquity : Profit generated from shareholder equity  
ReturnOnAssets : Profit generated from company assets  

#### Financial Health
DebtToEquity : Debt level relative to shareholder equity  
CurrentRatio : Ability to cover short-term liabilities  
QuickRatio : Liquidity excluding inventory  

#### Cash Flow Metrics
OperatingCashflow : Cash generated from business operations  
FreeCashflow : Cash remaining after capital expenditures  

#### Risk Metrics
Beta : Stock volatility relative to market  
52WeekHigh : Highest price in last 52 weeks  
52WeekLow : Lowest price in last 52 weeks  

#### Analyst & Market Sentiment
RecommendationMean : Average analyst rating score  
TargetMeanPrice : Average analyst price target  

#### Dividend & Shareholder Returns
DividendYield : Annual dividend relative to stock price  
PayoutRatio : Portion of earnings paid as dividends

#### IMPORTANT_FIELDS

#### Size & Market Position
- EnterpriseValue : True acquisition cost of company  

#### Valuation Metrics
- TrailingPE : High may indicate overvaluation or growth expectations  
- ForwardPE : Lower than TrailingPE suggests expected earnings growth  
- PEG : Around 1 = fairly valued relative to growth  
- PriceToBook : <1 may indicate undervaluation or distressed assets  
- PriceToSales : Useful for unprofitable growth companies  

#### Growth Metrics
RevenueGrowth : Shows demand expansion  
EarningsGrowth : Measures profitability acceleration  
EarningsQuarterlyGrowth : Detects recent momentum changes  

#### Profitability Metrics
ProfitMargins : Higher = efficient business model  
OperatingMargins : Core business strength indicator  
ReturnOnEquity : Measures management efficiency using capital  
ReturnOnAssets : Asset utilization effectiveness  

#### Financial Health
DebtToEquity : High values increase financial risk  
CurrentRatio : >1 indicates ability to pay short-term obligations  
QuickRatio : Conservative liquidity measurement  

#### Cash Flow Metrics
OperatingCashflow : Confirms earnings quality  
FreeCashflow : Key metric for long-term investors and valuation  

#### Risk Metrics
Beta : >1 more volatile, <1 more defensive  
52WeekHigh : Indicates momentum or resistance levels  
52WeekLow : Indicates downside risk or recovery potential  

#### Analyst & Market Sentiment
RecommendationMean : Lower value typically means stronger buy rating  
TargetMeanPrice : Used to estimate expected upside/downside  

#### Dividend & Shareholder Returns
DividendYield : Income generation from holding stock  
PayoutRatio : High ratio may limit future growth investments

### Test Features

#### ETF Analysis

##### Feature

1. 13F investment update
2. ETFs portfolio analysis - proportion
3. Newly added stocks on ETFs (ETF Analyst pick)

In [ ]:
spy = yf.Ticker('SPY')
soxl = yf.Ticker('SOXL')

spy.info

{'longBusinessSummary': 'The trust seeks to achieve its investment objective by holding a portfolio of the common stocks that are included in the index (the “Portfolio”), with the weight of each stock in the Portfolio substantially corresponding to the weight of such stock in the index.',
 'companyOfficers': [],
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 715.17,
 'open': 711.815,
 'dayLow': 709.25,
 'dayHigh': 712.88,
 'regularMarketPreviousClose': 715.17,
 'regularMarketOpen': 711.815,
 'regularMarketDayLow': 709.25,
 'regularMarketDayHigh': 712.88,
 'trailingPE': 28.216604,
 'volume': 37342531,
 'regularMarketVolume': 37342531,
 'averageVolume': 83543613,
 'averageVolume10days': 52177830,
 'averageDailyVolume10Day': 52177830,
 'bid': 711.7,
 'ask': 711.64,
 'bidSize': 1880,
 'askSize': 640,
 'yield': 0.0114,
 'totalAssets': 651588272128,
 'fiftyTwoWeekLow': 541.52,
 'fiftyTwoWeekHigh': 715.63,
 'allTimeHigh': 715.63,
 'allTimeLow': 42.8125,
 'fiftyDayAverage': 677.672,
 'twoHundredDayAverage': 669.10126,
 'trailingAnnualDividendRate': 5.662,
 'trailingAnnualDividendYield': 0.007916999,
 'navPrice': 715.02277,
 'currency': 'USD',
 'tradeable': False,
 'category': 'Large Blend',
 'ytdReturn': -4.34315,
 'beta3Year': 1.0,
 'fundFamily': 'State Street Investment Management',
 'fundInceptionDate': 727660800,
 'legalType': 'Exchange Traded Fund',
 'threeYearAverageReturn': 0.2169259,
 'fiveYearAverageReturn': 0.12902111,
 'quoteType': 'ETF',
 'symbol': 'SPY',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'ETF',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'POST',
 'shortName': 'State Street SPDR S&P 500 ETF T',
 'longName': 'State Street SPDR S&P 500 ETF Trust',
 'financialCurrency': 'USD',
 'averageDailyVolume3Month': 83543613,
 'fiftyTwoWeekLowChange': 170.16998,
 'fiftyTwoWeekLowChangePercent': 0.31424505,
 'fiftyTwoWeekRange': '541.52 - 715.63',
 'fiftyTwoWeekHighChange': -3.9400024,
 'fiftyTwoWeekHighChangePercent': -0.005505642,
 'fiftyTwoWeekChangePercent': 29.017532,
 'dividendYield': 1.14,
 'trailingThreeMonthReturns': -4.34315,
 'trailingThreeMonthNavReturns': -4.34315,
 'netAssets': 651588270000.0,
 'epsTrailingTwelveMonths': 25.222383,
 'sharesOutstanding': 917782016,
 'bookValue': 429.22,
 'fiftyDayAverageChange': 34.018005,
 'fiftyDayAverageChangePercent': 0.050198335,
 'twoHundredDayAverageChange': 42.588745,
 'twoHundredDayAverageChangePercent': 0.063650675,
 'netExpenseRatio': 0.0945,
 'marketCap': 653176274944,
 'priceToBook': 1.6581007,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'cryptoTradeable': False,
 'corporateActions': [],
 'postMarketTime': 1777420335,
 'regularMarketTime': 1777406400,
 'exchange': 'PCX',
 'messageBoardId': 'finmb_6160262',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 728317800000,
 'postMarketChangePercent': 0.10046887,
 'postMarketPrice': 712.405,
 'postMarketChange': 0.71502686,
 'regularMarketChange': -3.47998,
 'regularMarketDayRange': '709.25 - 712.88',
 'fullExchangeName': 'NYSEArca',
 'regularMarketChangePercent': -0.486595,
 'regularMarketPrice': 711.69,
 'trailingPegRatio': None}

##### ETF - fund data

In [ ]:
Objective :

In [ ]:
"""
ETF Groups Configuration
Used for dashboard, screening, and batch yfinance analysis.
"""

# -----------------------------
# Core / Broad Market ETFs
# -----------------------------
CORE_ETFS = [
    "SPY",  # S&P 500
    "IVV",  # iShares Core S&P 500
    "VOO",  # Vanguard S&P 500
    "QQQ",  # Nasdaq 100
    "DIA",  # Dow Jones
    "IWM",  # Russell 2000
    "VTI",  # Total US Market
    "VWO",  # Emerging Markets
    "VEA",  # Developed ex-US
    "ITOT", # Total US Market (iShares)
    "SCHB", # Schwab Broad Market
    "VT",   # Total World
]

# -----------------------------
# Sector ETFs
# -----------------------------
SECTOR_ETFS = [
    "XLF",  # Financials
    "XLK",  # Technology
    "XLE",  # Energy
    "XLV",  # Healthcare
    "XLI",  # Industrials
    "XLP",  # Consumer Staples
    "XLY",  # Consumer Discretionary
    "XLU",  # Utilities
    "XLB",  # Materials
    "XLRE", # Real Estate
]

# -----------------------------
# Thematic / Growth ETFs
# -----------------------------
THEMATIC_ETFS = [
    "ARKK",  # Innovation
    "ARKQ",  # Robotics & Autonomous
    "SMH",   # Semiconductors
    "SOXX",  # Semiconductors (iShares)
    "IGV",   # Software
    "BOTZ",  # Robotics & AI
    "ROBO",  # Robotics
    "FINX",  # Fintech
    "CIBR",  # Cybersecurity
    "HACK",  # Cybersecurity
]

# -----------------------------
# International ETFs
# -----------------------------
INTERNATIONAL_ETFS = [
    "EFA",   # Developed ex-US
    "IEFA",  # Core developed ex-US
    "IEMG",  # Emerging Markets
    "VXUS",  # Total International
    "EWJ",   # Japan
    "EWG",   # Germany
    "FXI",   # China
]

# -----------------------------
# Bonds / Fixed Income
# -----------------------------
BOND_ETFS = [
    "BND",  # Total Bond Market
    "AGG",  # Aggregate Bonds
    "TLT",  # 20+ Year Treasuries
    "IEF",  # 7-10 Year Treasuries
    "SHY",  # Short Term Treasuries
    "LQD",  # Investment Grade Corporate
    "HYG",  # High Yield Bonds
]

# -----------------------------
# Alternatives / Commodities / Hedge
# -----------------------------
ALTERNATIVE_ETFS = [
    "VIXY",  # Volatility
    "UVXY",  # Leveraged Volatility
    "GLD",   # Gold
    "SLV",   # Silver
    "USO",   # Oil
    "DBC",   # Commodities Basket
]

# -----------------------------
# Master Dictionary (for dashboards)
# -----------------------------
ETF_GROUPS = {
    "core": CORE_ETFS,
    "sectors": SECTOR_ETFS,
    "thematic": THEMATIC_ETFS,
    "international": INTERNATIONAL_ETFS,
    "bonds": BOND_ETFS,
    "alternatives": ALTERNATIVE_ETFS,
}

# -----------------------------
# Flattened universe (useful for batch downloads)
# -----------------------------
ALL_ETFS = sorted(set(
    CORE_ETFS
    + SECTOR_ETFS
    + THEMATIC_ETFS
    + INTERNATIONAL_ETFS
    + BOND_ETFS
    + ALTERNATIVE_ETFS
))

ALL_ETFS

['AGG',
 'ARKK',
 'ARKQ',
 'BND',
 'BOTZ',
 'CIBR',
 'DBC',
 'DIA',
 'EFA',
 'EWG',
 'EWJ',
 'FINX',
 'FXI',
 'GLD',
 'HACK',
 'HYG',
 'IEF',
 'IEFA',
 'IEMG',
 'IGV',
 'ITOT',
 'IVV',
 'IWM',
 'LQD',
 'QQQ',
 'ROBO',
 'SCHB',
 'SHY',
 'SLV',
 'SMH',
 'SOXX',
 'SPY',
 'TLT',
 'USO',
 'UVXY',
 'VEA',
 'VIXY',
 'VOO',
 'VT',
 'VTI',
 'VWO',
 'VXUS',
 'XLB',
 'XLE',
 'XLF',
 'XLI',
 'XLK',
 'XLP',
 'XLRE',
 'XLU',
 'XLV',
 'XLY']

In [ ]:
ETFs = [
    "SPY",   # S&P 500
    "IVV",   # iShares Core S&P 500
    "VOO",   # Vanguard S&P 500
    "QQQ",   # Nasdaq 100
    "QQQM",  # Nasdaq 100 (lower fee QQQ)
    "DIA",   # Dow Jones Industrial Average
    "IWM",   # Russell 2000 (small cap)
    "VTI",   # Total US Market
    "VWO",   # Emerging Markets
    "VEA",   # Developed Markets ex-US

    # Core / Broad additions
    "VT",    # Total World Stock Market
    "SCHB",  # Schwab Broad US Market
    "ITOT",  # iShares Total US Market
    "VXF",   # Extended Market (mid + small cap)

    # Growth / Index / Large Cap Growth
    "VOOG",  # S&P 500 Growth
    "VUG",   # Vanguard Growth ETF
    "SCHG",  # Schwab Large Cap Growth
    "MGK",   # Mega Cap Growth

    # Dividend / Value / Quality
    "SCHD",  # Schwab Dividend ETF
    "VIG",   # Dividend Appreciation
    "DVY",   # High Dividend Yield
    "HDV",   # High Dividend (iShares)
    "DGRO",  # Dividend Growth ETF

    # Sector / Thematic Index ETFs (common in dashboards)
    "XLK",   # Tech
    "XLF",   # Financials
    "XLV",   # Healthcare
    "XLE",   # Energy
    "SMH",   # Semiconductors

    # Topical ETFs

    # "GLD",  # SPDR Gold Shares
    # "SLV",  # iShares Silver Trust
    # "USO",  # United States Oil Fund
    # "TLT",  # iShares 20+ Year Treasury Bond ETF
    # "LQD",  # iShares iBoxx $ Investment Grade Corporate Bond ETF
    # "HYG",  # iShares iBoxx $ High Yield Corporate Bond ETF
    # "XLK",  # Technology Select Sector SPDR Fund
    # "XLF",  # Financial Select Sector SPDR Fund
    # "XLV",  # Health Care Select Sector SPDR Fund
    # "XLE",  # Energy Select Sector SPDR Fund
    # "XLI",  # Industrial Select Sector SPDR Fund
    # "XLP",  # Consumer Staples Select Sector SPDR Fund
    # "XLY",  # Consumer Discretionary Select Sector SPDR Fund
    # "XLB",  # Materials Select Sector SPDR Fund
    # "XLC",  # Communication Services Select Sector SPDR Fund
    # "XLU",  # Utilities Select Sector SPDR Fund
    # "XLRE", # Real Estate Select Sector SPDR Fund
    # "ARKK", # ARK Innovation ETF
    # "SMH",  # VanEck Semiconductor ETF
    # "IGV",  # iShares Expanded Tech-Software Sector ETF
    # "SOXX", # iShares Semiconductor ETF
]

In [ ]:
print(yf.Ticker('VT').funds_data.top_holdings)
print(yf.Ticker('SCHD').funds_data.top_holdings)

                                              Name  Holding Percent
Symbol
NVDA                                   NVIDIA Corp         0.039744
AAPL                                     Apple Inc         0.035600
MSFT                                Microsoft Corp         0.026729
AMZN                                Amazon.com Inc         0.019452
GOOGL                         Alphabet Inc Class A         0.016295
AVGO                                  Broadcom Inc         0.013919
2330.TW  Taiwan Semiconductor Manufacturing Co Ltd         0.013699
GOOG                          Alphabet Inc Class C         0.013199
META                    Meta Platforms Inc Class A         0.012162
TSLA                                     Tesla Inc         0.010213
                              Name  Holding Percent
Symbol
CVX                   Chevron Corp         0.046819
COP                 ConocoPhillips         0.043304
VZ      Verizon Communications Inc         0.040609
MRK                 Merck & Co Inc         0.040586
KO                    Coca-Cola Co         0.040367
PEP                    PepsiCo Inc         0.039545
TXN          Texas Instruments Inc         0.038074
AMGN                     Amgen Inc         0.038036
PG             Procter & Gamble Co         0.037789
ABT            Abbott Laboratories         0.037235

In [ ]:
from collections import Counter

symbols = []
for etf in ETFs:
  symbols.extend(list(yf.Ticker(etf).funds_data.top_holdings.index))

# Count frequencies
symbol_counts = Counter(symbols)

# Sort unique symbols by frequency descending
sorted_unique_tickers = [item[0] for item in symbol_counts.most_common()]

print(f"Found {len(sorted_unique_tickers)} unique tickers across {len(ETFs)} ETFs.")
print("Top 100 most frequent tickers:")
print(sorted_unique_tickers[:100])

# Store in a variable for later use
famous_tickers_sorted = sorted_unique_tickers

generate_stocks_df(famous_tickers_sorted)

Found 110 unique tickers across 28 ETFs.
Top 20 most frequent tickers:
['MSFT', 'AVGO', 'AAPL', 'NVDA', 'AMZN', 'GOOGL', 'GOOG', 'META', 'TSLA', 'BRK-B', 'LLY', 'JPM', 'MRK', 'XOM', 'JNJ', 'WMT', 'AMGN', 'V', 'CVX', 'PG', 'ABBV', 'GS', 'HD', 'AXP', 'BE', '2330.TW', 'COP', 'VZ', 'KO', 'TXN', 'ABT', 'PM', 'AMD', 'AMAT', 'LRCX', 'CAT', 'SHW', 'MCD', 'CDE', 'FN', 'NXT', 'SATS', 'CRDO', 'KTOS', 'AEIS', 'STRL', 'HL', '0700.HK', '9988.HK', 'RELIANCE.NS', '00939', 'HDFCBANK.NS', '2308.TW', 'PDD', '2317.TW', '1810.HK', '005930.KS', 'ASML.AS', '000660.KS', 'NOVN.SW', 'AZN.L', 'HSBA.L', 'ROP.SW', 'SHEL.L', 'NESN.SW', 'RY', 'MRVL', 'NET', 'LNG', 'SNOW', 'FERG', 'ALNY', 'MSTR', 'RBLX', 'INSM', 'PEP', 'COST', 'PFE', 'MO', 'PRU', 'OKE', 'TROW', 'LYB', 'EIX', 'GIS', 'HPQ', 'PGR', 'MU', 'PLTR', 'CSCO', 'MA', 'BAC', 'WFC', 'C', 'MS', 'UNH', 'TMO', 'GILD', 'ISRG', 'EOG']

/tmp/ipykernel_32791/4021647762.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([df, new_row], ignore_index=True)
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: 00939"}}}

,shortName,sector,industry,marketCap,currentPrice,forwardPE,pegRatio,revenueGrowth,earningsGrowth,forwardEps,profitMargins,returnOnEquity,freeCashflow,debtToEquity,beta,averageVolume,heldPercentInstitutions,shortPercentOfFloat,trailingAnnualDividendYield,payoutRatio
symbol,,,,,,,,,,,,,,,,,,,,
MSFT,Microsoft Corporation,Technology,Software - Infrastructure,3190348316672,429.25,22.680920,1.34,0.167,0.598,18.925600,0.39044,0.34391,53640626176,31.539,1.107,36251950,0.75979,0.0112,0.008192,0.2128
AVGO,Broadcom Inc.,Technology,Semiconductors,1893062410240,399.83,22.068169,0.92,0.295,0.316,18.117950,0.36572,0.33371,25503750144,82.704,1.253,25727867,0.79686,0.0118,0.005930,0.4717
AAPL,Apple Inc.,Technology,Consumer Electronics,3974331367424,270.71,28.902985,2.44,0.157,0.183,9.366160,0.27037,1.52021,106312753152,102.630,1.109,45360691,0.65232,0.0092,0.003849,0.1304
NVDA,NVIDIA Corporation,Technology,Semiconductors,5181096853504,213.17,18.966686,0.74,0.732,0.956,11.239180,0.55603,1.01485,58128998400,7.255,2.335,175938301,0.69668,0.0122,0.000185,0.0082
AMZN,"Amazon.com, Inc.",Consumer Cyclical,Internet Retail,2792879292416,259.70,27.471336,1.91,0.136,0.050,9.453490,0.10834,0.22286,23793125376,43.435,1.383,52037331,0.67072,0.0095,0.000000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KMI,"Kinder Morgan, Inc.",Energy,Oil & Gas Midstream,70727213056,31.79,21.531084,3.73,0.138,0.360,1.476470,0.18917,0.10597,1646875008,98.840,0.630,13658255,0.69519,0.0250,0.037964,0.7852
TSM,Taiwan Semiconductor Manufactur,Technology,Semiconductors,2034832244736,392.34,20.336739,1.30,0.351,0.584,19.292180,0.46505,0.36210,721560469504,17.131,1.251,13656839,0.15700,0.0053,0.041977,0.2793
ASML,ASML Holding N.V. - New York Re,Technology,Semiconductor Equipment & Materials,533633892352,1384.56,29.015360,2.25,0.132,0.192,47.718178,0.29713,0.52236,8243274752,12.989,1.382,1706859,0.18679,0.0019,0.004119,0.2582
ADI,"Analog Devices, Inc.",Technology,Semiconductors,187109130240,383.26,29.153360,0.99,0.304,1.167,13.146340,0.23024,0.07862,4139530752,25.753,1.053,3996488,0.93101,0.0228,0.010367,0.7239
KLAC,KLA Corporation,Technology,Semiconductor Equipment & Materials,237684785152,1808.97,37.485466,2.15,0.072,0.409,48.257900,0.35764,1.00726,3222999808,111.778,1.435,1030696,0.93471,0.0284,0.003895,0.2154

In [ ]:
def format_pct(value):
    if pd.isna(value) or not isinstance(value, (int, float)):
        return value
    return f"{value * 100:.4f}%"

all_etf_holdings = []

for etf_symbol in ETFs:
    try:
        ticker = yf.Ticker(etf_symbol)
        funds_data = ticker.funds_data

        if funds_data and hasattr(funds_data, 'top_holdings') and funds_data.top_holdings is not None:
            holdings_df = funds_data.top_holdings
            # Add an 'ETF' column to identify the source ETF
            holdings_df['ETF'] = etf_symbol+" "
            all_etf_holdings.append(holdings_df)
        else:
            print(f"No top holdings data found for ETF: {etf_symbol}")

    except Exception as e:
        print(f"Could not fetch data for ETF {etf_symbol}: {e}")

# Concatenate all individual ETF holdings DataFrames into one
if all_etf_holdings:
    combined_holdings_df = pd.concat(all_etf_holdings)
    # Order by 'Symbol' (index) and then 'Holding Percent'
    # Resetting index to make 'Symbol' a column for sorting
    combined_holdings_df = combined_holdings_df.reset_index().rename(columns={'index': 'Symbol'})
    combined_holdings_df = combined_holdings_df.groupby(['Symbol', 'Name']).aggregate(
        {'Holding Percent': 'mean', 'ETF': 'sum'}
    ).sort_values(by=['Holding Percent'], ascending=[False])
    combined_holdings_df["Holding Percent"] = combined_holdings_df["Holding Percent"].apply(format_pct)
    # combined_holdings_df = combined_holdings_df.sort_values(by=['Symbol', 'Holding Percent'], ascending=[True, True])


    # Display the result
    display(combined_holdings_df)
else:
    print("No ETF holdings data was collected.")

,,Holding Percent,ETF
Symbol,Name,,
TSM,Taiwan Semiconductor Manufacturing Co Ltd ADR,11.7268%,SMH
NVDA,NVIDIA Corp,10.1277%,SPY IVV VOO QQQ QQQM VTI VT SCHB ITOT VOOG VUG...
XOM,Exxon Mobil Corp,9.9539%,VIG HDV DGRO XLE
CVX,Chevron Corp,9.6418%,SCHD HDV XLE
CAT,Caterpillar Inc,9.3882%,DIA
...,...,...,...
INSM,Insmed Inc,0.4690%,VXF
KTOS,Kratos Defense & Security Solutions Inc,0.4335%,IWM
AEIS,Advanced Energy Industries Inc,0.4138%,IWM
STRL,Sterling Infrastructure Inc,0.4132%,IWM
HL,Hecla Mining Co,0.4025%,IWM

In [ ]:
data = soxl.funds_data

# show fund description
print("-------------------------------FUND DESCRIPTION-------------------------------------")
print("Fund description : ", data.description)

# show operational information
print("\n-------------------------------OPERATIONAL INFO-------------------------------------")
print("Fund Overview : ", data.fund_overview)
print("Fund Operation : \n", data.fund_operations)

# show holdings related information
print("\n-------------------------------HOLDINGS RELATED INFORMATION-------------------------")
print("Asset Classes : ", data.asset_classes)
print("Top Holdings : \n", data.top_holdings)
print("Equity Holdings : \n", data.equity_holdings)
print("Bond Holdings : \n", data.bond_holdings)
print("Bond Ratings : ", data.bond_ratings)
print("Sector Weight : ", data.sector_weightings)

-------------------------------FUND DESCRIPTION-------------------------------------
Fund description :  The fund invests at least 80% of its net assets in financial instruments, such as swap agreements, securities of the index, and ETFs that track the index, that, in combination, provide 3X daily leveraged exposure to the index, consistent with the fund's investment objective. The index is a rules-based, modified float-adjusted market capitalization-weighted index that tracks the performance of the thirty largest U.S. listed semiconductor companies. The fund is non-diversified.

-------------------------------OPERATIONAL INFO-------------------------------------
Fund Overview :  {'categoryName': 'Trading--Leveraged Equity', 'family': 'Direxion Funds', 'legalType': 'Exchange Traded Fund'}
Fund Operation :
                                     SOXL Category Average
Attributes
Annual Report Expense Ratio       0.0075              0.0
Annual Holdings Turnover          2.5000             <NA>
Total Net Assets             223345.8400        223345.84

-------------------------------HOLDINGS RELATED INFORMATION-------------------------
Asset Classes :  {'cashPosition': 0.1273, 'stockPosition': 0.8727, 'bondPosition': 0.0, 'preferredPosition': 0.0, 'convertiblePosition': 0.0, 'otherPosition': 0.0}
Top Holdings :
                               Name  Holding Percent
Symbol
NVDA                   NVIDIA Corp         0.052320
AVGO                  Broadcom Inc         0.051761
MU           Micron Technology Inc         0.048082
AMD     Advanced Micro Devices Inc         0.042561
AMAT         Applied Materials Inc         0.038380
Equity Holdings :
                            SOXL Category Average
Average
Price/Earnings          0.02329             <NA>
Price/Book              0.13164             <NA>
Price/Sales             0.10605             <NA>
Price/Cashflow          0.03596             <NA>
Median Market Cap          <NA>             <NA>
3 Year Earnings Growth     <NA>             <NA>
Bond Holdings :
                 SOXL Category Average
Average
Duration        <NA>             <NA>
Maturity        <NA>             <NA>
Credit Quality  <NA>             <NA>
Bond Ratings :  {'us_government': 0.0}
Sector Weight :  {'realestate': 0.0, 'consumer_cyclical': 0.0, 'basic_materials': 0.0, 'consumer_defensive': 0.0, 'technology': 1.0, 'communication_services': 0.0, 'financial_services': 0.0, 'utilities': 0.0, 'industrials': 0.0, 'energy': 0.0, 'healthcare': 0.0}

#### Dashboard

In [ ]:
"""
Financial Dashboard — yfinance + Plotly
Run: pip install yfinance plotly pandas
     python financial_dashboard.py
"""

import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots


# ── Config ────────────────────────────────────────────────
TICKER  = "AAPL"
PERIOD  = "6mo"     # 1mo 3mo 6mo 1y 2y 5y
MA_DAYS = 20        # Moving average window
SHOW_MA  = True
SHOW_RSI = True
RSI_PERIOD = 14
# ─────────────────────────────────────────────────────────


def calc_ma(series: pd.Series, window: int) -> pd.Series:
    return series.rolling(window=window).mean()


def calc_rsi(series: pd.Series, period: int = 14) -> pd.Series:
    delta = series.diff()
    gain  = delta.clip(lower=0).rolling(period).mean()
    loss  = (-delta.clip(upper=0)).rolling(period).mean()
    rs    = gain / loss
    return 100 - (100 / (1 + rs))


def fmt_large(n):
    if n is None: return "N/A"
    if n >= 1e12: return f"${n/1e12:.2f}T"
    if n >= 1e9:  return f"${n/1e9:.2f}B"
    if n >= 1e6:  return f"${n/1e6:.2f}M"
    return f"${n:,.0f}"

def fmt(v, prefix="", suffix="", decimals=2):
    if v is None or (isinstance(v, float) and (v != v)):
        return "N/A"
    return f"{prefix}{v:.{decimals}f}{suffix}"


def fetch_data(ticker, period):
    print(f"\nFetching {ticker} ({period})...")
    t    = yf.Ticker(ticker)
    hist = t.history(period=period)
    info = t.info
    try:
        recs = t.recommendations
    except Exception:
        recs = None
    return hist, info, recs


def print_metrics(info):
    print("\n" + "="*52)
    print(f"  {info.get('shortName', TICKER)}  ({info.get('symbol', TICKER)})")
    print(f"  {info.get('sector','')} · {info.get('industry','')}")
    print("="*52)
    rows = [
        ("Current Price",    fmt(info.get("currentPrice"),   prefix="$")),
        ("Market Cap",       fmt_large(info.get("marketCap"))),
        ("P/E Ratio",        fmt(info.get("trailingPE"))),
        ("Forward P/E",      fmt(info.get("forwardPE"))),
        ("EPS (TTM)",        fmt(info.get("trailingEps"),    prefix="$")),
        ("Forward EPS",      fmt(info.get("forwardEps"),     prefix="$")),
        ("Price/Book",       fmt(info.get("priceToBook"))),
        ("Dividend Yield",   fmt(info.get("dividendYield"),  suffix="%", decimals=2) if info.get("dividendYield") else "N/A"),
        ("Beta",             fmt(info.get("beta"))),
        ("52w High",         fmt(info.get("fiftyTwoWeekHigh"), prefix="$")),
        ("52w Low",          fmt(info.get("fiftyTwoWeekLow"),  prefix="$")),
        ("Target Price",     fmt(info.get("targetMeanPrice"),  prefix="$")),
        ("Analyst Rating",   str(info.get("recommendationKey", "N/A")).upper()),
        ("# Analysts",       str(info.get("numberOfAnalystOpinions", "N/A"))),
        ("Return on Equity", fmt(info.get("returnOnEquity") and info.get("returnOnEquity")*100, suffix="%")),
        ("Profit Margin",    fmt(info.get("profitMargins")  and info.get("profitMargins")*100,  suffix="%")),
    ]
    for label, value in rows:
        print(f"  {label:<22} {value}")
    print("="*52)


def print_recommendations(recs):
    if recs is None or recs.empty:
        print("\nNo analyst recommendation data available.")
        return
    print("\nAnalyst Recommendations (recent):")
    print(f"  {'Period':<12} {'StrongBuy':>9} {'Buy':>6} {'Hold':>6} {'Sell':>6} {'StrongSell':>11}")
    print("  " + "-"*54)
    for _, row in recs.tail(6).iterrows():
        print(f"  {str(row.get('period','')):<12}"
              f"  {int(row.get('strongBuy',0)):>7}"
              f"  {int(row.get('buy',0)):>6}"
              f"  {int(row.get('hold',0)):>6}"
              f"  {int(row.get('sell',0)):>6}"
              f"  {int(row.get('strongSell',0)):>10}")


def build_plot(hist, ticker):
    rows = 2 if SHOW_RSI else 1
    row_heights = [0.7, 0.3] if SHOW_RSI else [1.0]

    fig = make_subplots(
        rows=rows, cols=1,
        shared_xaxes=True,
        row_heights=row_heights,
        vertical_spacing=0.04,
        subplot_titles=[f"{ticker} — Price", "RSI (14)"] if SHOW_RSI else [f"{ticker} — Price"],
    )

    # ── Close price ──
    fig.add_trace(go.Scatter(
        x=hist.index, y=hist["Close"].round(2),
        name="Close", line=dict(color="#3266ad", width=1.5),
        hovertemplate="%{x|%b %d, %Y}<br>Close: $%{y:.2f}<extra></extra>",
    ), row=1, col=1)

    # ── Moving average ──
    if SHOW_MA:
        ma = calc_ma(hist["Close"], MA_DAYS)
        fig.add_trace(go.Scatter(
            x=hist.index, y=ma.round(2),
            name=f"MA {MA_DAYS}d", line=dict(color="#e07d28", width=1.5, dash="dot"),
            hovertemplate=f"MA{MA_DAYS}: $%{{y:.2f}}<extra></extra>",
        ), row=1, col=1)

    # ── RSI ──
    if SHOW_RSI:
        rsi = calc_rsi(hist["Close"], RSI_PERIOD)
        fig.add_trace(go.Scatter(
            x=hist.index, y=rsi.round(2),
            name="RSI", line=dict(color="#a32d2d", width=1.5),
            hovertemplate="RSI: %{y:.1f}<extra></extra>",
        ), row=2, col=1)

        # Overbought / oversold bands
        for level, color, label in [(70, "rgba(163,45,45,0.08)", "Overbought"),
                                     (30, "rgba(59,109,17,0.08)", "Oversold")]:
            fig.add_hline(y=level, line=dict(color="gray", width=0.8, dash="dash"), row=2, col=1)
        fig.update_yaxes(range=[0, 100], row=2, col=1)

    fig.update_layout(
        title=f"{ticker} Financial Dashboard",
        height=620,
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
        xaxis_rangeslider_visible=False,
        plot_bgcolor="white",
        paper_bgcolor="white",
        font=dict(family="Arial", size=12),
    )
    fig.update_xaxes(showgrid=True, gridcolor="#e8e8e8")
    fig.update_yaxes(showgrid=True, gridcolor="#e8e8e8")

    return fig


def main():
    hist, info, recs = fetch_data(TICKER, PERIOD)

    if hist.empty:
        print(f"No price data returned for {TICKER}. Check the ticker symbol.")
        return

    print_metrics(info)
    print_recommendations(recs)

    fig = build_plot(hist, TICKER)
    fig.show()
    print("\nChart opened in browser.")


if __name__ == "__main__":
    main()

Fetching AAPL (6mo)...

====================================================
  Apple Inc.  (AAPL)
  Technology · Consumer Electronics
====================================================
  Current Price          $271.06
  Market Cap             $3.98T
  P/E Ratio              34.35
  Forward P/E            28.92
  EPS (TTM)              $7.89
  Forward EPS            $9.37
  Price/Book             45.19
  Dividend Yield         0.38%
  Beta                   1.11
  52w High               $288.62
  52w Low                $193.25
  Target Price           $297.71
  Analyst Rating         BUY
  # Analysts             40
  Return on Equity       152.02%
  Profit Margin          27.04%
====================================================

Analyst Recommendations (recent):
  Period       StrongBuy    Buy   Hold   Sell  StrongSell
  ------------------------------------------------------
  0m                  7      24      14       1           1
  -1m                 6      25      15       1           1
  -2m                 5      25      16       1           1
  -3m                 6      24      15       1           2

Chart opened in browser.

#### Scoring model - scratch 1

In [ ]:
FACTOR_FIELDS = {
    "profitability": [
        "returnOnEquity",
        "profitMargins",
        "operatingMargins"
    ],
    "growth": [
        "revenueGrowth",
        "earningsGrowth",
        "earningsQuarterlyGrowth"
    ],
    "valuation": [
        "forwardPE",
        "pegRatio",
        "enterpriseToEbitda"
    ],
    "financial_health": [
        "debtToEquity",
        "currentRatio",
        "freeCashflow"
    ],
    "sentiment": [
        "heldPercentInstitutions",
        "shortPercentOfFloat"
    ]
}

In [ ]:
def normalize(value, low, high, reverse=False):
    if value is None:
        return 0.5

    value = max(min(value, high), low)
    score = (value - low) / (high - low)

    return 1 - score if reverse else score

In [ ]:
def score_metric(key, value):

    rules = {
        # profitability (higher better)
        "returnOnEquity": (0, 0.40, False),
        "profitMargins": (0, 0.30, False),
        "operatingMargins": (0, 0.30, False),

        # growth
        "revenueGrowth": (-0.1, 0.40, False),
        "earningsGrowth": (-0.2, 0.50, False),
        "earningsQuarterlyGrowth": (-0.2, 0.60, False),

        # valuation (lower better)
        "forwardPE": (5, 60, True),
        "pegRatio": (0.5, 3, True),
        "enterpriseToEbitda": (5, 40, True),

        # financial health
        "debtToEquity": (0, 200, True),
        "currentRatio": (0.5, 3, False),
        "freeCashflow": (0, 20_000_000_000, False),

        # sentiment
        "heldPercentInstitutions": (0.2, 0.9, False),
        "shortPercentOfFloat": (0, 0.20, True),
    }

    if key not in rules:
        return 0.5

    low, high, reverse = rules[key]
    return normalize(value, low, high, reverse)

In [ ]:
def score_factor(info, fields):
    scores = []

    for f in fields:
        value = info.get(f)
        if value is not None:
            scores.append(score_metric(f, value))

    return sum(scores) / len(scores) if scores else 0.5

In [ ]:
FACTOR_WEIGHTS = {
    "profitability": 0.25,
    "growth": 0.25,
    "valuation": 0.20,
    "financial_health": 0.20,
    "sentiment": 0.10,
}


def quant_score(info):

    total = 0

    for factor, fields in FACTOR_FIELDS.items():
        factor_score = score_factor(info, fields)
        total += factor_score * FACTOR_WEIGHTS[factor]

    return round(total * 100, 2)

In [ ]:
stocks = generate_stocks_df(TOP_200_US_TICKERS)
stocks['score'] = [quant_score(yf.Ticker(x).info) for x in TOP_200_US_TICKERS]
stocks.sort_values(by='score', ascending=False)

/tmp/ipykernel_32791/471467504.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([df, new_row], ignore_index=True)

,Name,Sector,Industry,Market Cap,Price,Forward PE,PEG,Revenue Growth,Earnings Growth,Forward EPS,...,ROE,Free Cashflow,Debt to Equity,Beta,Avg. Volume,Insr. Ownership,Short Float,Dividend Yield,Payout Ratio,score
symbol,,,,,,,,,,,,,,,,,,,,,
MU,"Micron Technology, Inc.",Technology,Semiconductors,568705024000,504.29,4.987579,0.29,1.963,7.560,101.10917,...,0.39823,2893499904,14.902,1.606,41710662,0.82273,0.0323,0.000944,0.0217,90.16
NVDA,NVIDIA Corporation,Technology,Semiconductors,5181096853504,213.17,18.966686,0.74,0.732,0.956,11.23918,...,1.01485,58128998400,7.255,2.335,175938301,0.69668,0.0122,0.000185,0.0082,89.29
TSM,Taiwan Semiconductor Manufactur,Technology,Semiconductors,2034832244736,392.34,20.336739,1.30,0.351,0.584,19.29218,...,0.36210,721560469504,17.131,1.251,13656839,0.15734,0.0053,0.041977,0.2793,87.16
BLK,"BlackRock, Inc.",Financial Services,Asset Management,163095920640,1049.76,17.306175,1.33,0.270,0.459,60.65812,...,NaN,None,24.367,1.493,861744,0.82485,0.0126,0.020211,0.5376,84.41
MSFT,Microsoft Corporation,Technology,Software - Infrastructure,3190348316672,429.25,22.680920,1.34,0.167,0.598,18.92560,...,0.34391,53640626176,31.539,1.107,36251950,0.75914,0.0112,0.008192,0.2128,81.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SO,Southern Company (The),Utilities,Utilities - Regulated Electric,106428784640,94.41,19.185633,2.66,0.101,-0.221,4.92087,...,0.11043,-3460124928,190.586,0.405,5745883,0.72116,0.0223,0.031353,0.7500,33.13
TSLA,"Tesla, Inc.",Consumer Cyclical,Auto Manufacturers,1412227268608,376.02,148.310290,5.14,0.158,0.083,2.53536,...,0.04901,5251999744,18.738,1.915,63744409,0.44641,0.0213,0.000000,0.0000,32.90
WMT,Walmart Inc.,Consumer Defensive,Discount Stores,1017018646528,127.59,38.871418,4.87,0.056,-0.190,3.28236,...,0.21847,10554250240,64.443,0.661,21893473,0.38860,0.0156,0.007367,0.3443,29.72
SBUX,Starbucks Corporation,Consumer Cyclical,Restaurants,110831099904,97.28,33.425533,NaN,0.055,-0.625,2.91035,...,NaN,-1439387520,NaN,0.944,7634880,0.84505,0.0442,0.025130,2.0417,27.75
F,Ford Motor Company,Consumer Cyclical,Auto Manufacturers,49737416704,12.40,6.667240,8.48,-0.048,NaN,1.85984,...,-0.20193,1758625024,460.639,1.710,56768337,0.67935,0.0000,0.048038,0.6410,20.63

#### Scoring model - scratch 2

In [ ]:
def load_yf_data(symbol):

    t = yf.Ticker(symbol)

    try:
        return {
            "price": t.history(period="10y")["Close"],
            "income": t.quarterly_income_stmt,
            "balance": t.balance_sheet,
            "cashflow": t.cashflow,
            "info": t.info
        }
    except:
        return None

In [ ]:
def price_factors(price):

    returns = price.pct_change()

    momentum_12m = price.iloc[-1] / price.iloc[-252] - 1
    volatility = returns.std() * (252**0.5)

    return {
        "momentum_12m": momentum_12m,
        "volatility": volatility
    }

def income_factors(income):

    try:
        revenue = income.loc["Total Revenue"]
        net_income = income.loc["Net Income"]

        revenue_growth = revenue.pct_change().mean()
        earnings_growth = net_income.pct_change().mean()

        return {
            "rev_growth_q": revenue_growth,
            "earn_growth_q": earnings_growth
        }
    except:
        return {}


def balance_factors(balance):

    try:
        debt = balance.loc["Total Debt"].iloc[0]
        equity = balance.loc["Stockholders Equity"].iloc[0]
        cash = balance.loc["Cash And Cash Equivalents"].iloc[0]

        debt_equity = debt / equity

        return {
            "de_ratio_real": debt_equity,
            "cash_level": cash
        }
    except:
        return {}


def cashflow_factors(cashflow):

    try:
        fcf = cashflow.loc["Free Cash Flow"].iloc[0]
        op_cf = cashflow.loc["Operating Cash Flow"].iloc[0]

        quality = fcf / op_cf

        return {
            "fcf_quality": quality
        }
    except:
        return {}

def build_factor_row(symbol):

    data = load_yf_data(symbol)
    if data is None:
        return None

    factors = {}

    factors.update(price_factors(data["price"]))
    factors.update(income_factors(data["income"]))
    factors.update(balance_factors(data["balance"]))
    factors.update(cashflow_factors(data["cashflow"]))

    return factors

def build_factor_table(df):

    rows = {}

    for symbol in df.index:
        print("Processing", symbol)

        factors = build_factor_row(symbol)

        if factors:
            rows[symbol] = factors

    return pd.DataFrame.from_dict(rows, orient="index")

def normalize_factors(factors_df):

    scored = factors_df.copy()

    for col in scored.columns:
        scored[col] = scored[col].rank(pct=True)

    return scored

In [ ]:
FACTOR_WEIGHTS = {
    "momentum_12m": 0.25,
    "rev_growth_q": 0.15,
    "earn_growth_q": 0.15,
    "fcf_quality": 0.15,
    "de_ratio_real": -0.10,   # lower debt better
    "volatility": -0.10,      # lower risk better
    "cash_level": 0.10
}

def compute_quant_score(norm_df):

    score = pd.Series(0, index=norm_df.index)

    for factor, weight in FACTOR_WEIGHTS.items():
        if factor in norm_df:
            score += norm_df[factor] * weight

    return score

In [ ]:
def add_quant_score(df):

    factor_table = build_factor_table(df)

    norm_factors = normalize_factors(factor_table)

    scores = compute_quant_score(norm_factors)

    df["score"] = scores

    return df.sort_values("score", ascending=False)

In [ ]:
sp500_tickers = [
"AAPL","MSFT","NVDA","AMZN","GOOGL","GOOG","META","BRK-B","LLY","AVGO",
"TSLA","JPM","V","UNH","XOM","MA","JNJ","HD","PG","COST",
"MRK","ABBV","CVX","ADBE","PEP","KO","CRM","WMT","NFLX","BAC",
"AMD","MCD","ACN","CSCO","LIN","ABT","TMO","ORCL","DHR","WFC",
"TXN","PM","DIS","VZ","INTU","AMAT","NEE","CMCSA","QCOM","IBM",
"CAT","RTX","PFE","GE","LOW","INTC","SPGI","UNP","HON","UPS",
"MS","BLK","GS","DE","NOW","SCHW","ISRG","AMGN","PLD","LMT",
"ADI","ELV","GILD","MDT","SBUX","CI","CVS","CB","BKNG",
"ZTS","T","MO","REGN","SYK","SO","EOG","BDX","DUK","ITW",
"EQIX","APD","TJX","PGR","CSX","USB","SHW","VRTX","PNC","CME",
"CL","NSC","AON","ICE","NOC","EMR","FDX","MCO","WM","HUM",
"ROP","GD","ETN","PSA","MPC","FIS","ADP","FCX","COF","HCA",
"AIG","MET","KMI","AEP","TRV","PSX","OXY","EXC","ALL","SLB",
"ROST","MAR","AFL","TEL","AZO","JCI","D","ECL","CTAS","WMB",
"ORLY","MSI","WELL","SPG","PAYX","SRE","GIS","PCAR","DLR","FTNT",
"AMP","PRU","CMG","HLT","OTIS","AME","ED","IQV","EA","VLO",
"FAST","ROK","IDXX","F","DD","VRSK","YUM","BKR","KMB","STZ",
"KR","LEN","CTSH","DAL","OKE","CTVA","WEC","XEL","HPQ",
"PEG","GPN","ANET","VICI","CBRE","CHTR","DTE","EFX","MTD","MLM",
"TSCO","RMD","KHC","EXR","ZBH","KEYS","FANG","NUE","AWK","CARR",
"FRC","ALB","PWR","MGM","HIG","MPWR","LHX","A","GLW","XYL",
"ULTA","RJF","LYV","MKC","ARE","HOLX","AVB","EQR","ESS","SBAC",
"AMCR","MAA","INVH","NVR","WY","WST","WRB","PKG","VTR","UDR",
"LUV","UAL","AAL","NDAQ","IP","RF","FDS","CMS","LH","AEE",
"APA","HPE","CDW","FLT","IRM","TPR","BRO","IEX","WAB","CNP",
"NI","NRG","MRO","PPL","MOS","ROL","DOV","CAG","HAS","DRI",
"SJM","CPB","HSY","HRL","MKTX","BBWI","BIO","AKAM","ETSY","POOL",
"CHD","LKQ","PHM","DHI","JBHT","SNA","PNR","RHI","AIZ","KMX",
"SEE","ZBRA","QRVO","PAYC","GNRC","BWA","TECH","TFX","SWKS",
"UHS","PKI","WRK","TER","CRL","OMC","MHK","ALLE","FFIV",
"NDSN","JKHY","LDOS","HII","CBOE","DXCM","STE","ALGN","TAP","INCY",
"BIO","CDNS","SNPS","PTC","TYL","BR","AKR","PEAK","RE",
"FMC","EMN","MOS","CF","NTRS","BEN","IVZ","STT","KEY","HBAN",
"FITB","CFG","ZION","MTB","CINF","AJG","L","PFG","UNM","AOS",
"PNW","EVRG","LNT","AES","ATO","OGE","WTRG","FE","ES","ETR",
"PCG","ED","EIX","NRG","EXE","SO","DUK","SRE","NEE","AEP"
]
df = generate_stocks_df(sp500_tickers)
score_df = add_quant_score(df)

/tmp/ipykernel_32791/4021647762.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([df, new_row], ignore_index=True)

Processing AAPL
Processing MSFT
Processing NVDA
Processing AMZN
Processing GOOGL

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing GOOG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing META
Processing BRK-B

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing LLY

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AVGO

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing TSLA

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing JPM

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing V
Processing UNH

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing XOM

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing MA

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing JNJ

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing HD
Processing PG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing COST

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing MRK

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ABBV
Processing CVX
Processing ADBE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing PEP

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing KO

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CRM
Processing WMT

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing NFLX
Processing BAC

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AMD

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing MCD

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ACN

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CSCO
Processing LIN

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ABT
Processing TMO
Processing ORCL

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing DHR

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing WFC
Processing TXN

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing PM

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing DIS

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing VZ
Processing INTU

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AMAT
Processing NEE
Processing CMCSA

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing QCOM

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing IBM
Processing CAT

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing RTX
Processing PFE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing GE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing LOW
Processing INTC
Processing SPGI

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing UNP

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing HON

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing UPS
Processing MS

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing BLK
Processing GS

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing DE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing NOW
Processing SCHW
Processing ISRG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AMGN
Processing PLD

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing LMT
Processing ADI

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ELV

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing GILD

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing MDT

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing SBUX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CI

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CVS

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CB

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing BKNG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ZTS

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing T
Processing MO

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing REGN

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing SYK
Processing SO

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing EOG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing BDX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing DUK

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ITW
Processing EQIX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing APD
Processing TJX
Processing PGR

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CSX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing USB
Processing SHW

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing VRTX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing PNC
Processing CME
Processing CL

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing NSC

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AON

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ICE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing NOC

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing EMR

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing FDX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing MCO

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing WM

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing HUM

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ROP

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing GD

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ETN
Processing PSA

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing MPC

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing FIS

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ADP
Processing FCX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing COF

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing HCA

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AIG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing MET
Processing KMI

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AEP

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing TRV
Processing PSX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing OXY

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing EXC
Processing ALL

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing SLB

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ROST

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing MAR
Processing AFL

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing TEL

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AZO

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing JCI

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing D

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ECL
Processing CTAS
Processing WMB

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ORLY
Processing MSI

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing WELL

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing SPG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing PAYX

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing SRE
Processing GIS

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing PCAR
Processing DLR

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing FTNT

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AMP
Processing PRU

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CMG
Processing HLT

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing OTIS

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AME
Processing ED

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing IQV
Processing EA

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing VLO
Processing FAST
Processing ROK

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing IDXX
Processing F

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing DD

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing VRSK

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing YUM
Processing BKR

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing KMB

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing STZ

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing KR

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing LEN
Processing CTSH

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing DAL

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing OKE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CTVA

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing WEC
Processing XEL
Processing HPQ

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing PEG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing GPN
Processing ANET

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing VICI

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CBRE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CHTR

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing DTE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing EFX
Processing MTD
Processing MLM

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing TSCO
Processing RMD

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing KHC

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing EXR

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing ZBH
Processing KEYS
Processing FANG

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing NUE

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing AWK

/tmp/ipykernel_32791/2859713539.py:19: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  revenue_growth = revenue.pct_change().mean()
/tmp/ipykernel_32791/2859713539.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  earnings_growth = net_income.pct_change().mean()

Processing CARR
Processing FRC

ERROR:yfinance:$FRC: possibly delisted; no price data found  (period=10y) (Yahoo error = "No data found, symbol may be delisted")

IndexError: single positional indexer is out-of-bounds

In [ ]:
score_df.sort_values("score", ascending=False).drop(labels=["Sector"], axis=1)

KeyError: "['Sector'] not found in axis"

# Scrath